datasets:
  retrieval:
    kazakh:
      name: "shyngys879/Kazakh-Wiki-RAG-Dataset"
      role: "kazakh_retrieval_corpus"

    russian:
      name: "kaengreg/sberquad-retrieval"
      role: "russian_retrieval_dataset"

  instruction:
    kazakh:
      name: "AmanMussa/kazakh-instruction-v2"
      role: "kazakh_sft_instruction_data"

    russian:
      name: "Den4ikAI/russian_instructions_2"
      role: "russian_sft_instruction_data"

