"""Generate answers from RAG prompts with a local Transformers model."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .prompt_builder import RAGPrompt


@dataclass(frozen=True)
class GeneratedAnswer:
    """Text generated by the baseline RAG generator."""

    answer_text: str
    prompt_text: str
    model_name: str
    metadata: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "answer_text": self.answer_text,
            "prompt_text": self.prompt_text,
            "model_name": self.model_name,
            "metadata": self.metadata,
        }


class TransformersGenerator:
    """Simple non-streaming wrapper around a Transformers text-generation pipeline."""

    def __init__(
        self,
        model_name: str,
        max_new_tokens: int = 512,
        temperature: float = 0.2,
        do_sample: bool = False,
        device_map: str | None = "auto",
        torch_dtype: str | None = "auto",
    ) -> None:
        model_name = model_name.strip()
        if not model_name:
            raise ValueError("model_name must not be empty.")
        if max_new_tokens <= 0:
            raise ValueError("max_new_tokens must be positive.")
        if temperature < 0:
            raise ValueError("temperature must be non-negative.")

        self.model_name = model_name
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.do_sample = do_sample
        self.device_map = device_map
        self.torch_dtype = torch_dtype
        self._pipeline: Any | None = None

    def generate(self, prompt: RAGPrompt | str) -> GeneratedAnswer:
        prompt_text = prompt.prompt_text if isinstance(prompt, RAGPrompt) else str(prompt)
        prompt_text = prompt_text.strip()
        if not prompt_text:
            raise ValueError("prompt_text must not be empty.")

        generator = self._load_pipeline()
        outputs = generator(
            prompt_text,
            max_new_tokens=self.max_new_tokens,
            temperature=self.temperature,
            do_sample=self.do_sample,
            return_full_text=False,
        )
        answer_text = self._extract_answer_text(outputs)

        return GeneratedAnswer(
            answer_text=answer_text,
            prompt_text=prompt_text,
            model_name=self.model_name,
            metadata={
                "max_new_tokens": self.max_new_tokens,
                "temperature": self.temperature,
                "do_sample": self.do_sample,
                "device_map": self.device_map,
                "torch_dtype": self.torch_dtype,
                "generator": "transformers.pipeline",
            },
        )

    def _load_pipeline(self) -> Any:
        if self._pipeline is not None:
            return self._pipeline

        try:
            from transformers import pipeline
        except ImportError as exc:
            raise RuntimeError("TransformersGenerator requires the transformers package.") from exc

        pipeline_kwargs: dict[str, Any] = {
            "task": "text-generation",
            "model": self.model_name,
        }
        if self.device_map is not None:
            pipeline_kwargs["device_map"] = self.device_map
        if self.torch_dtype is not None:
            pipeline_kwargs["torch_dtype"] = self.torch_dtype

        self._pipeline = pipeline(**pipeline_kwargs)
        return self._pipeline

    @staticmethod
    def _extract_answer_text(outputs: Any) -> str:
        if isinstance(outputs, list) and outputs:
            first = outputs[0]
            if isinstance(first, dict):
                generated_text = first.get("generated_text")
                if generated_text is not None:
                    return str(generated_text).strip()

        raise ValueError("Unexpected transformers generation output format.")
